# -*- coding: utf-8 -*-
"""Week8 (Jacobson/Karns Algorithm) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fio4NFmpV4EskSP-PVM0kG3gSqAGiXMd
"""

def update_rto_demo(srtt, rttvar, r_sample):
    if srtt is None:
        srtt = r_sample
        rttvar = r_sample / 2
    else:

        rttvar = (1 - 0.25) * rttvar + 0.25 * abs(srtt - r_sample)

        srtt = (1 - 0.125) * srtt + 0.125 * r_sample

    rto = srtt + 4 * rttvar
    return srtt, rttvar, rto
samples = [100, 105, 300, 110, 100]
s, v = None, None
for r in samples:
    s, v, rto = update_rto_demo(s, v, r)
    print(f"Sample: {r}ms | SRTT: {s:.1f} | RTTVAR: {v:.1f} | RTO: {rto:.1f}ms")