# -*- coding: utf-8 -*-
"""Week7_lab_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4ABlzbI1zGulJYymLZoTj3QFAHwJWnk
"""

"""
EC 441 – Week 7: Network & Transport Layer Lab Simulation
Consolidated from: demo_protocols_l17_2.py and demo_rdt_throughput_l18_2.py
"""

import ipaddress
import struct
import socket
import random

def run_network_layer_demos():
    print("="*60)
    print("SECTION 1: NETWORK LAYER (IPv4, ICMP, FRAGMENTATION, NAT)")
    print("="*60)

    # Constructing a sample 20-byte IPv4 header
    sample_header = struct.pack(
        "!BBHHHBBH4s4s",
        0x45, 0x00, 84, 0xABCD, 0x4000, 64, 1, 0x0000,
        socket.inet_aton("10.0.0.2"), socket.inet_aton("142.250.80.46")
    )

    ver_ihl = sample_header[0]
    version = (ver_ihl >> 4) & 0xF
    ihl = ver_ihl & 0xF
    total_length = struct.unpack("!H", sample_header[2:4])[0]
    flags_offset = struct.unpack("!H", sample_header[6:8])[0]
    frag_offset = flags_offset & 0x1FFF

    print(f"[IPv4 Decode] Version: {version}, IHL: {ihl}, Total Len: {total_length}")
    print(f"[IPv4 Decode] Fragment Offset: {frag_offset} (bytes: {frag_offset * 8})\n")

    def get_fragments(total_size, header_size, mtu):
        payload = total_size - header_size
        max_p_per_frag = ((mtu - header_size) // 8) * 8 # Must be multiple of 8[cite: 9]
        frags = []
        offset = 0
        while offset < payload:
            f_payload = min(max_p_per_frag, payload - offset)
            frags.append({"offset": offset // 8, "size": f_payload + header_size, "mf": 1 if offset + f_payload < payload else 0})
            offset += f_payload
        return frags

    print(f"[Fragmentation] Splitting 4000B datagram into MTU 1500:")
    for i, f in enumerate(get_fragments(4000, 20, 1500)):
        print(f"  Frag {i+1}: Size={f['size']}, Offset={f['offset']}, MF={f['mf']}[cite: 9]")

    print(f"\n[NAT] Simulating Port-Address Translation (PAT):")
    nat_table = [
        {"lan": "10.0.0.2:5001", "wan": "128.197.10.1:40001", "dest": "google.com:443"},
        {"lan": "10.0.0.3:5002", "wan": "128.197.10.1:40002", "dest": "amazon.com:443"}
    ]
    for e in nat_table:
        print(f"  Internal {e['lan']} -> NAT {e['wan']} -> External {e['dest']}[cite: 9]")

def run_transport_layer_demos():
    print("\n" + "="*60)
    print("SECTION 2: TRANSPORT LAYER (RDT & THROUGHPUT)")
    print("="*60)

    # Packet: 1500 bytes. Satellite RTT: 600ms. BW: 1Gbps
    pkt_bits = 1500 * 8
    bw_bps = 1 * 10**9
    rtt_s = 0.600
    t_tx = pkt_bits / bw_bps
    util = t_tx / (rtt_s + t_tx)

    print(f"[BDP] Satellite Link Utilization (Stop-and-Wait): {util:.5%}")

    # --- 2. Stop-and-Wait Simulation ---
    def simulate_saw(num_packets, loss_rate):
        transmitted = 0
        delivered = 0
        while delivered < num_packets:
            transmitted += 1
            if random.random() > loss_rate: # Success
                delivered += 1
        return transmitted

    loss = 0.15
    total_tx = simulate_saw(10, loss)
    print(f"[RDT Sim] To deliver 10 packets with {loss:.0%} loss, it took {total_tx} attempts.[cite: 10]")

    # Formula: GBN = (1-p) / (1 + (N-1)p)
    p = 0.10
    N = 8
    t_gbn = (1 - p) / (1 + (N - 1) * p)
    t_sr = (1 - p)

    print(f"\n[Efficiency at p={p}, N={N}]")
    print(f"  Go-Back-N Throughput: {t_gbn:.3f}")
    print(f"  Selective Repeat Throughput: {t_sr:.3f}[cite: 10]")

if __name__ == "__main__":
    run_network_layer_demos()
    run_transport_layer_demos()