# -*- coding: utf-8 -*-
"""Week 4: Multiple Access Protocols and Ethernet: Addressing, Switching, and ARP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_fqViWOiHIHVy1-IxjjsYg5WrLv6V82
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

def pure_aloha(slots=10000, G=1.0):
    success = 0


    tx = np.random.poisson(G, slots)

    for t in range(slots):

        window = tx[max(0, t-1):min(slots, t+2)]

        if tx[t] == 1 and np.sum(window) == 1:
            success += 1

    return success / slots


def slotted_aloha(slots=10000, G=1.0):
    tx = np.random.poisson(G, slots)
    success = np.sum(tx == 1)
    return success / slots


pure = pure_aloha()
slotted = slotted_aloha()

print("Pure ALOHA efficiency:", pure)
print("Slotted ALOHA efficiency:", slotted)

plt.bar(["Pure ALOHA", "Slotted ALOHA"], [pure, slotted])
plt.title("ALOHA Efficiency ")
plt.ylabel("Throughput")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def simulate_aloha():
    G_vals = np.linspace(0.01, 3.0, 50)
    trials = 10000

    pure_s = []
    slotted_s = []

    for G in G_vals:

        tx = np.random.poisson(G, trials)
        slotted_s.append(np.sum(tx == 1) / trials)


        success = 0
        tx_pure = np.random.poisson(G, trials)
        for t in range(1, trials-1):
            if tx_pure[t] == 1 and tx_pure[t-1] == 0 and tx_pure[t+1] == 0:
                success += 1
        pure_s.append(success / trials)


    theory_pure = G_vals * np.exp(-2 * G_vals)
    theory_slotted = G_vals * np.exp(-G_vals)

    plt.figure(figsize=(10, 6))
    plt.scatter(G_vals, pure_s, label="Simulated Pure", alpha=0.5)
    plt.plot(G_vals, theory_pure, 'r--', label="Theoretical Pure")
    plt.scatter(G_vals, slotted_s, label="Simulated Slotted", alpha=0.5)
    plt.plot(G_vals, theory_slotted, 'b--', label="Theoretical Slotted")

    plt.title("ALOHA Throughput: Simulation vs. Theory")
    plt.xlabel("Offered Load (G)")
    plt.ylabel("Throughput (S)")
    plt.legend()
    plt.grid(True)
    plt.savefig("aloha_results.png")
    plt.show()

if __name__ == "__main__":
    simulate_aloha()