# -*- coding: utf-8 -*-
"""ip_calc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vz2evg2wf65ykAwbOCRt59Pr5IKU9djy
"""

import ipaddress


network = ipaddress.ip_network('192.168.10.0/27')

print(f"Network Address: {network.network_address}")
print(f"Broadcast Address: {network.broadcast_address}")
print(f"Number of Usable Hosts: {network.num_addresses - 2}")
print(f"First Usable IP: {list(network.hosts())[0]}")
print(f"Last Usable IP: {list(network.hosts())[-1]}")