# -*- coding: utf-8 -*-
"""Python analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2GDf_nDe4_FWB_28tLajCOAZvYbJ0Hh
"""

import numpy as np

def entropy(p):
    return -sum([x * np.log2(x) for x in p if x > 0])

fair_coin = [0.5, 0.5]
biased_coin = [0.9, 0.1]

print("Fair coin entropy:", entropy(fair_coin))
print("Biased coin entropy:", entropy(biased_coin))