# -*- coding: utf-8 -*-
"""routing_experiment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGm19TrLezwtnUvA4Yr020qDb7Si-qa1
"""

# Combining logic from demo_dijkstra_l15.py and demo_bellmanford_l16.py

import time

OFFICE_EDGES = [
    ("HQ", "BR1", 2),
    ("HQ", "BR2", 5),
    ("BR1", "REMOTE", 2),
    ("BR2", "REMOTE", 1)
]

def run_lab_comparison():
    print(" WEEK 6 LAB: ROUTING CONVERGENCE EXPERIMENT Lecture 15 and 16 ")

    print("\n[PART 1: LINK-STATE ANALYSIS]")
    print("In Link-State, HQ receives the full map immediately.")

    path_cost = 2 + 2
    print(f"Dijkstra identifies optimal path: HQ -> BR1 -> REMOTE (Cost: {path_cost})")

    # 2. Simulate Distance Vector (Bellman-Ford) logic
    print("\n[PART 2: DISTANCE VECTOR GOSSIP]")
    print("Round 1: HQ only knows BR1(2) and BR2(5).")
    print("Round 2: HQ hears from BR1 that REMOTE is 2 away. HQ updates REMOTE cost to 4.")

    # 3. THE "CRISIS" - Link HQ-BR1 Fails
    print("\n[PART 3: THE LINK FAILURE CRISIS]")
    print("CRITICAL FAILURE: Link HQ---BR1 is severed.")

    # Dijkstra behavior
    print("\nDijkstra Response:")
    print("LSA (Link State Advertisement) floods the network. HQ re-runs Dijkstra.")
    print("New Path: HQ -> BR2 -> REMOTE (Cost: 6). Convergence is nearly instant.")

    print("\nDistance Vector Response (The Danger Zone):")
    print("BR1 is gone. HQ asks BR2: 'How do I get to REMOTE?'")
    print("If BR2 doesn't use Poison Reverse, it says: 'I can get there in 3 via HQ!'")
    print("HQ says: 'Great, then I can get there in 1 + 3 = 4 via you!'")
    print("This starts a Count-to-Infinity loop...")

    for i in range(5, 10):
        print(f"   DV Update: HQ cost to REMOTE is now {i}...")
        time.sleep(0.1)
    print("   ...Contining until infinity (16 in RIP).")

if __name__ == "__main__":
    run_lab_comparison()



